language: c

os:
  - linux
  - osx

compiler:
  - clang

matrix:
  allow_failures:
    - os: linux

env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=RELEASE

addons:
  apt:
    sources:
      - sourceline: 'ppa:plt/racket'
      - llvm-toolchain-trusty-6.0
    packages:
      - llvm
      - racket

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install llvm && brew install racket; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then raco setup; else sudo raco setup; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then raco pkg install --auto compiler-lib; else raco pkg install compiler-lib; fi

script:
  - raco test racket-llvm.rkt
