language: c

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: linux

addons:
  apt:
    sources:
      - sourceline: 'ppa:plt/racket'
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - llvm-dev-6.0
      - racket

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update
    && brew install llvm
    && export PATH="/usr/local/opt/llvm/bin:$PATH"
    && brew install racket
    && raco pkg install --auto compiler-lib;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH="/usr/lib/llvm-6.0/bin:$PATH"; `ls llvm-config --libdir`; fi

script:
  - raco test racket-llvm.rkt
